version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=app-cluster
      - network.host=0.0.0.0
      - http.port=9200
      - discovery.type=single-node
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    container_name: kb01
    environment:
      SERVER_NAME: 'kibana'
      SERVER_HOST: '0.0.0.0'
      ELASTICSEARCH_HOSTS: 'http://elasticsearch:9200'
    ports:
      - 5601:5601

volumes:
  esdata01:
    driver: local